server:
  port: 8080

spring:
  application:
    name: aurabeauty
  data:
    mongodb:
      uri: mongodb://localhost:27017/cosmetics_db
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B2E50645367566B5970
  expiration: 86400000 # 24h in ms

cloudinary:
  cloud-name: your-cloud-name
  api-key: your-api-key
  api-secret: your-api-secret
